# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(219, 171)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnDraw = QtWidgets.QPushButton(self.centralwidget)
        self.btnDraw.setObjectName("btnDraw")
        self.verticalLayout.addWidget(self.btnDraw)
        self.btnSubplot1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnSubplot1.setObjectName("btnSubplot1")
        self.verticalLayout.addWidget(self.btnSubplot1)
        self.btnSubplot2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnSubplot2.setObjectName("btnSubplot2")
        self.verticalLayout.addWidget(self.btnSubplot2)
        self.btnSubplot3 = QtWidgets.QPushButton(self.centralwidget)
        self.btnSubplot3.setObjectName("btnSubplot3")
        self.verticalLayout.addWidget(self.btnSubplot3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 219, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnDraw.setText(_translate("MainWindow", "한 figure에 두개"))
        self.btnSubplot1.setText(_translate("MainWindow", "fig.subplots"))
        self.btnSubplot2.setText(_translate("MainWindow", "plt.subplots"))
        self.btnSubplot3.setText(_translate("MainWindow", "plt.subplot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
