# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 265)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menuTool = QtWidgets.QToolButton(self.centralwidget)
        self.menuTool.setGeometry(QtCore.QRect(80, 0, 91, 71))
        self.menuTool.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.menuTool.setCheckable(False)
        self.menuTool.setAutoExclusive(False)
        self.menuTool.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.menuTool.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.menuTool.setAutoRaise(False)
        self.menuTool.setArrowType(QtCore.Qt.NoArrow)
        self.menuTool.setObjectName("menuTool")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(180, 0, 91, 71))
        self.toolButton.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.toolButton.setCheckable(False)
        self.toolButton.setAutoExclusive(False)
        self.toolButton.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setAutoRaise(False)
        self.toolButton.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton.setObjectName("toolButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 564, 20))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionLeftAlign = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/align/images/align_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLeftAlign.setIcon(icon)
        self.actionLeftAlign.setObjectName("actionLeftAlign")
        self.actionRightAlign = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/align/images/align_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRightAlign.setIcon(icon1)
        self.actionRightAlign.setObjectName("actionRightAlign")
        self.actionCenterAlign = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/align/images/align_center.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCenterAlign.setIcon(icon2)
        self.actionCenterAlign.setObjectName("actionCenterAlign")
        self.actionJustAlign = QtWidgets.QAction(MainWindow)
        self.actionJustAlign.setCheckable(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/align/images/align_justify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJustAlign.setIcon(icon3)
        self.actionJustAlign.setObjectName("actionJustAlign")
        self.toolBar.addAction(self.actionLeftAlign)
        self.toolBar.addAction(self.actionRightAlign)
        self.toolBar.addAction(self.actionCenterAlign)
        self.toolBar.addAction(self.actionJustAlign)
        self.toolBar.addSeparator()
        self.menu.addAction(self.actionLeftAlign)
        self.menu.addAction(self.actionRightAlign)
        self.menu.addAction(self.actionCenterAlign)
        self.menu.addAction(self.actionJustAlign)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Main Window"))
        self.menuTool.setText(_translate("MainWindow", "Align"))
        self.toolButton.setText(_translate("MainWindow", "Align"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menu.setTitle(_translate("MainWindow", "정렬"))
        self.actionLeftAlign.setText(_translate("MainWindow", "왼쪽 정렬"))
        self.actionLeftAlign.setToolTip(_translate("MainWindow", "왼쪽 맞춤"))
        self.actionRightAlign.setText(_translate("MainWindow", "오른쪽 정렬"))
        self.actionRightAlign.setToolTip(_translate("MainWindow", "오른쪽 맞춤"))
        self.actionCenterAlign.setText(_translate("MainWindow", "가운데 정렬"))
        self.actionCenterAlign.setToolTip(_translate("MainWindow", "가운데 맞춤"))
        self.actionJustAlign.setText(_translate("MainWindow", "양쪽 정렬"))
        self.actionJustAlign.setToolTip(_translate("MainWindow", "양쪽맞춤"))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
