# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(212, 173)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.titleLabel)
        self.titleLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.titleLineEdit.setText("")
        self.titleLineEdit.setObjectName("titleLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titleLineEdit)
        self.xlabelLabel = QtWidgets.QLabel(self.centralwidget)
        self.xlabelLabel.setObjectName("xlabelLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.xlabelLabel)
        self.xlabelLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.xlabelLineEdit.setObjectName("xlabelLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.xlabelLineEdit)
        self.ylabelLabel = QtWidgets.QLabel(self.centralwidget)
        self.ylabelLabel.setObjectName("ylabelLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ylabelLabel)
        self.ylabelLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ylabelLineEdit.setObjectName("ylabelLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ylabelLineEdit)
        self.legendLabel = QtWidgets.QLabel(self.centralwidget)
        self.legendLabel.setObjectName("legendLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.legendLabel)
        self.legendLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.legendLineEdit.setObjectName("legendLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.legendLineEdit)
        self.legendLocLabel = QtWidgets.QLabel(self.centralwidget)
        self.legendLocLabel.setObjectName("legendLocLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.legendLocLabel)
        self.legendLocComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.legendLocComboBox.setObjectName("legendLocComboBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.legendLocComboBox)
        self.btnDraw = QtWidgets.QPushButton(self.centralwidget)
        self.btnDraw.setObjectName("btnDraw")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.btnDraw)
        self.horizontalLayout.addLayout(self.formLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "title"))
        self.xlabelLabel.setText(_translate("MainWindow", "xlabel"))
        self.ylabelLabel.setText(_translate("MainWindow", "ylabel"))
        self.legendLabel.setText(_translate("MainWindow", "legend"))
        self.legendLocLabel.setText(_translate("MainWindow", "legend loc"))
        self.btnDraw.setText(_translate("MainWindow", "Draw"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
