# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_sol.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(240, 347)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cal = QtWidgets.QCalendarWidget(self.centralwidget)
        self.cal.setObjectName("cal")
        self.verticalLayout.addWidget(self.cal)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Label_2 = QtWidgets.QLabel(self.centralwidget)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.DateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.DateEdit.setObjectName("DateEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DateEdit)
        self.Label_3 = QtWidgets.QLabel(self.centralwidget)
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.TimeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.TimeEdit.setObjectName("TimeEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.TimeEdit)
        self.DateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.DateTimeEdit.setObjectName("DateTimeEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.DateTimeEdit)
        self.Label = QtWidgets.QLabel(self.centralwidget)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.verticalLayout.addLayout(self.formLayout)
        self.lblMsg = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMsg.sizePolicy().hasHeightForWidth())
        self.lblMsg.setSizePolicy(sizePolicy)
        self.lblMsg.setMinimumSize(QtCore.QSize(0, 31))
        self.lblMsg.setMaximumSize(QtCore.QSize(16777215, 31))
        self.lblMsg.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lblMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMsg.setObjectName("lblMsg")
        self.verticalLayout.addWidget(self.lblMsg)
        self.btnToday = QtWidgets.QPushButton(self.centralwidget)
        self.btnToday.setObjectName("btnToday")
        self.verticalLayout.addWidget(self.btnToday)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.DateTimeEdit.dateChanged['QDate'].connect(self.cal.setSelectedDate)
        self.DateTimeEdit.timeChanged['QTime'].connect(self.TimeEdit.setTime)
        self.DateTimeEdit.dateChanged['QDate'].connect(self.DateEdit.setDate)
        self.cal.clicked['QDate'].connect(self.DateTimeEdit.setDate)
        self.TimeEdit.timeChanged['QTime'].connect(self.DateTimeEdit.setTime)
        self.DateEdit.dateChanged['QDate'].connect(self.DateTimeEdit.setDate)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label_2.setText(_translate("MainWindow", "날짜"))
        self.Label_3.setText(_translate("MainWindow", "시간"))
        self.Label.setText(_translate("MainWindow", "날짜와 시간"))
        self.lblMsg.setText(_translate("MainWindow", "선택한 날짜는 2020년 01월 01일 입니다."))
        self.btnToday.setText(_translate("MainWindow", "현재날짜, 현재시간 표시"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
