# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(346, 192)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 2, 1, 1)
        self.widOption = QtWidgets.QWidget(Dialog)
        self.widOption.setObjectName("widOption")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widOption)
        self.verticalLayout.setContentsMargins(9, 6, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chkWhole = QtWidgets.QCheckBox(self.widOption)
        self.chkWhole.setObjectName("chkWhole")
        self.verticalLayout.addWidget(self.chkWhole)
        self.chkBack = QtWidgets.QCheckBox(self.widOption)
        self.chkBack.setObjectName("chkBack")
        self.verticalLayout.addWidget(self.chkBack)
        self.chkSelection = QtWidgets.QCheckBox(self.widOption)
        self.chkSelection.setObjectName("chkSelection")
        self.verticalLayout.addWidget(self.chkSelection)
        self.gridLayout.addWidget(self.widOption, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblFind = QtWidgets.QLabel(Dialog)
        self.lblFind.setObjectName("lblFind")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblFind)
        self.cboFind = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboFind.sizePolicy().hasHeightForWidth())
        self.cboFind.setSizePolicy(sizePolicy)
        self.cboFind.setMinimumSize(QtCore.QSize(180, 0))
        self.cboFind.setMaximumSize(QtCore.QSize(180, 16777215))
        self.cboFind.setEditable(True)
        self.cboFind.setObjectName("cboFind")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cboFind)
        self.lblReplace = QtWidgets.QLabel(Dialog)
        self.lblReplace.setObjectName("lblReplace")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblReplace)
        self.cboReplace = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboReplace.sizePolicy().hasHeightForWidth())
        self.cboReplace.setSizePolicy(sizePolicy)
        self.cboReplace.setEditable(True)
        self.cboReplace.setObjectName("cboReplace")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cboReplace)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.chkCase = QtWidgets.QCheckBox(Dialog)
        self.chkCase.setObjectName("chkCase")
        self.verticalLayout_2.addWidget(self.chkCase)
        self.chkFromStart = QtWidgets.QCheckBox(Dialog)
        self.chkFromStart.setChecked(True)
        self.chkFromStart.setObjectName("chkFromStart")
        self.verticalLayout_2.addWidget(self.chkFromStart)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.chkWhole.setText(_translate("Dialog", "Whole words"))
        self.chkBack.setText(_translate("Dialog", "Search backward"))
        self.chkSelection.setText(_translate("Dialog", "Search Selection"))
        self.lblFind.setText(_translate("Dialog", "찾기 :"))
        self.lblReplace.setText(_translate("Dialog", "바꾸기 : "))
        self.chkCase.setText(_translate("Dialog", "Match case"))
        self.chkFromStart.setText(_translate("Dialog", "Search from start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
