# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(228, 221)
        MainWindow.setStyleSheet("")
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblRed = QtWidgets.QLabel(self.centralwidget)
        self.lblRed.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblRed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblRed.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRed.setObjectName("lblRed")
        self.horizontalLayout.addWidget(self.lblRed)
        self.lblGreen = QtWidgets.QLabel(self.centralwidget)
        self.lblGreen.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblGreen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblGreen.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGreen.setObjectName("lblGreen")
        self.horizontalLayout.addWidget(self.lblGreen)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btnCase1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnCase1.setObjectName("btnCase1")
        self.verticalLayout.addWidget(self.btnCase1)
        self.btnCase2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnCase2.setObjectName("btnCase2")
        self.verticalLayout.addWidget(self.btnCase2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 228, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblRed.setText(_translate("MainWindow", "RED"))
        self.lblGreen.setText(_translate("MainWindow", "GREEN"))
        self.btnCase1.setText(_translate("MainWindow", "Case1 동작"))
        self.btnCase2.setText(_translate("MainWindow", "Case2 동작"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
