# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 146)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cboColormap = QtWidgets.QComboBox(self.centralwidget)
        self.cboColormap.setObjectName("cboColormap")
        self.cboColormap.addItem("")
        self.cboColormap.addItem("")
        self.cboColormap.addItem("")
        self.cboColormap.addItem("")
        self.cboColormap.addItem("")
        self.horizontalLayout.addWidget(self.cboColormap)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinAlpha = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinAlpha.setMaximum(1.0)
        self.spinAlpha.setSingleStep(0.1)
        self.spinAlpha.setProperty("value", 1.0)
        self.spinAlpha.setObjectName("spinAlpha")
        self.horizontalLayout_2.addWidget(self.spinAlpha)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btnCmapScatter = QtWidgets.QPushButton(self.centralwidget)
        self.btnCmapScatter.setObjectName("btnCmapScatter")
        self.verticalLayout.addWidget(self.btnCmapScatter)
        self.btnScatter = QtWidgets.QPushButton(self.centralwidget)
        self.btnScatter.setObjectName("btnScatter")
        self.verticalLayout.addWidget(self.btnScatter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "colormap"))
        self.cboColormap.setItemText(0, _translate("MainWindow", "viridis"))
        self.cboColormap.setItemText(1, _translate("MainWindow", "plasma"))
        self.cboColormap.setItemText(2, _translate("MainWindow", "inferno"))
        self.cboColormap.setItemText(3, _translate("MainWindow", "magma"))
        self.cboColormap.setItemText(4, _translate("MainWindow", "cividis"))
        self.label_2.setText(_translate("MainWindow", "alpha"))
        self.btnCmapScatter.setText(_translate("MainWindow", "colormap scatter"))
        self.btnScatter.setText(_translate("MainWindow", "scatter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
