# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 152)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.marker = QtWidgets.QLineEdit(self.centralwidget)
        self.marker.setObjectName("marker")
        self.horizontalLayout_2.addWidget(self.marker)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.btnDrawPlot1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnDrawPlot1.setObjectName("btnDrawPlot1")
        self.gridLayout.addWidget(self.btnDrawPlot1, 0, 0, 1, 1)
        self.btnTwoWindow = QtWidgets.QPushButton(self.centralwidget)
        self.btnTwoWindow.setObjectName("btnTwoWindow")
        self.gridLayout.addWidget(self.btnTwoWindow, 3, 0, 1, 1)
        self.btnDrawPlotList = QtWidgets.QPushButton(self.centralwidget)
        self.btnDrawPlotList.setObjectName("btnDrawPlotList")
        self.gridLayout.addWidget(self.btnDrawPlotList, 1, 1, 1, 1)
        self.btnDrawPlotXY = QtWidgets.QPushButton(self.centralwidget)
        self.btnDrawPlotXY.setObjectName("btnDrawPlotXY")
        self.gridLayout.addWidget(self.btnDrawPlotXY, 2, 0, 1, 1)
        self.btnDrawPlotListXY = QtWidgets.QPushButton(self.centralwidget)
        self.btnDrawPlotListXY.setObjectName("btnDrawPlotListXY")
        self.gridLayout.addWidget(self.btnDrawPlotListXY, 2, 1, 1, 1)
        self.btnDrawPlot2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnDrawPlot2.setObjectName("btnDrawPlot2")
        self.gridLayout.addWidget(self.btnDrawPlot2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnDrawSelect = QtWidgets.QPushButton(self.centralwidget)
        self.btnDrawSelect.setObjectName("btnDrawSelect")
        self.horizontalLayout_3.addWidget(self.btnDrawSelect)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chkScaleX = QtWidgets.QCheckBox(self.groupBox)
        self.chkScaleX.setChecked(True)
        self.chkScaleX.setObjectName("chkScaleX")
        self.horizontalLayout.addWidget(self.chkScaleX)
        self.chkScaleY = QtWidgets.QCheckBox(self.groupBox)
        self.chkScaleY.setChecked(True)
        self.chkScaleY.setObjectName("chkScaleY")
        self.horizontalLayout.addWidget(self.chkScaleY)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btnScale = QtWidgets.QPushButton(self.groupBox)
        self.btnScale.setObjectName("btnScale")
        self.verticalLayout.addWidget(self.btnScale)
        self.horizontalLayout_4.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 460, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Marker"))
        self.btnDrawPlot1.setText(_translate("MainWindow", "선그래프 1개 그리기"))
        self.btnTwoWindow.setText(_translate("MainWindow", "창2개 띄우기"))
        self.btnDrawPlotList.setText(_translate("MainWindow", "이차원 리스트 사용"))
        self.btnDrawPlotXY.setText(_translate("MainWindow", "X.Y 좌표지정"))
        self.btnDrawPlotListXY.setText(_translate("MainWindow", "이차원 리스트 좌표지정"))
        self.btnDrawPlot2.setText(_translate("MainWindow", "선그래프 2개 그리기"))
        self.btnDrawSelect.setText(_translate("MainWindow", "선택적 그래프 출력"))
        self.groupBox.setTitle(_translate("MainWindow", "Scale"))
        self.chkScaleX.setText(_translate("MainWindow", "scalex"))
        self.chkScaleY.setText(_translate("MainWindow", "scaley"))
        self.btnScale.setText(_translate("MainWindow", "Scale"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
