# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(177, 145)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cboColumn = QtWidgets.QComboBox(self.centralwidget)
        self.cboColumn.setObjectName("cboColumn")
        self.horizontalLayout_3.addWidget(self.cboColumn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cboHittype = QtWidgets.QComboBox(self.centralwidget)
        self.cboHittype.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cboHittype.setObjectName("cboHittype")
        self.cboHittype.addItem("")
        self.cboHittype.addItem("")
        self.cboHittype.addItem("")
        self.cboHittype.addItem("")
        self.horizontalLayout.addWidget(self.cboHittype)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btnHist = QtWidgets.QPushButton(self.centralwidget)
        self.btnHist.setObjectName("btnHist")
        self.verticalLayout.addWidget(self.btnHist)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 177, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "column"))
        self.label_2.setText(_translate("MainWindow", "bins"))
        self.lineEdit.setText(_translate("MainWindow", "10"))
        self.label.setText(_translate("MainWindow", "histtype"))
        self.cboHittype.setItemText(0, _translate("MainWindow", "bar"))
        self.cboHittype.setItemText(1, _translate("MainWindow", "barstacked"))
        self.cboHittype.setItemText(2, _translate("MainWindow", "step"))
        self.cboHittype.setItemText(3, _translate("MainWindow", "stepfilled"))
        self.btnHist.setText(_translate("MainWindow", "histogram"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
