# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(457, 325)
        MainWindow.setStyleSheet("")
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnList = QtWidgets.QPushButton(self.centralwidget)
        self.btnList.setObjectName("btnList")
        self.verticalLayout.addWidget(self.btnList)
        self.btnTable = QtWidgets.QPushButton(self.centralwidget)
        self.btnTable.setObjectName("btnTable")
        self.verticalLayout.addWidget(self.btnTable)
        self.btninsert = QtWidgets.QPushButton(self.centralwidget)
        self.btninsert.setObjectName("btninsert")
        self.verticalLayout.addWidget(self.btninsert)
        self.btnImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnImage.setObjectName("btnImage")
        self.verticalLayout.addWidget(self.btnImage)
        self.btnImage2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnImage2.setObjectName("btnImage2")
        self.verticalLayout.addWidget(self.btnImage2)
        self.btnImage3 = QtWidgets.QPushButton(self.centralwidget)
        self.btnImage3.setObjectName("btnImage3")
        self.verticalLayout.addWidget(self.btnImage3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnSetPos = QtWidgets.QPushButton(self.centralwidget)
        self.btnSetPos.setObjectName("btnSetPos")
        self.verticalLayout_2.addWidget(self.btnSetPos)
        self.btnMovePos = QtWidgets.QPushButton(self.centralwidget)
        self.btnMovePos.setObjectName("btnMovePos")
        self.verticalLayout_2.addWidget(self.btnMovePos)
        self.btnChange = QtWidgets.QPushButton(self.centralwidget)
        self.btnChange.setObjectName("btnChange")
        self.verticalLayout_2.addWidget(self.btnChange)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 457, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnList.setText(_translate("MainWindow", "리스트 추가"))
        self.btnTable.setText(_translate("MainWindow", "테이블 추가"))
        self.btninsert.setText(_translate("MainWindow", "프레임 추가"))
        self.btnImage.setText(_translate("MainWindow", "이미지 추가1"))
        self.btnImage2.setText(_translate("MainWindow", "이미지 추가2"))
        self.btnImage3.setText(_translate("MainWindow", "기존 이미지 추가"))
        self.btnSetPos.setText(_translate("MainWindow", "setPos"))
        self.btnMovePos.setText(_translate("MainWindow", "movePos"))
        self.btnChange.setText(_translate("MainWindow", "선택내용 변경"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
