# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 283)
        MainWindow.setStyleSheet("")
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtEditor1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtEditor1.setDocumentTitle("")
        self.txtEditor1.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.txtEditor1.setPlainText("")
        self.txtEditor1.setOverwriteMode(False)
        self.txtEditor1.setBackgroundVisible(False)
        self.txtEditor1.setCenterOnScroll(False)
        self.txtEditor1.setObjectName("txtEditor1")
        self.horizontalLayout_2.addWidget(self.txtEditor1)
        self.txtEditor2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtEditor2.setDocumentTitle("")
        self.txtEditor2.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.txtEditor2.setOverwriteMode(False)
        self.txtEditor2.setBackgroundVisible(False)
        self.txtEditor2.setCenterOnScroll(False)
        self.txtEditor2.setObjectName("txtEditor2")
        self.horizontalLayout_2.addWidget(self.txtEditor2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSetDoc = QtWidgets.QPushButton(self.centralwidget)
        self.btnSetDoc.setAutoRepeat(False)
        self.btnSetDoc.setObjectName("btnSetDoc")
        self.horizontalLayout.addWidget(self.btnSetDoc)
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setAutoRepeat(False)
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout.addWidget(self.btnClear)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.btnLoad = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad.setAutoRepeat(False)
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout.addWidget(self.btnLoad)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 538, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.txtEditor1.zoomIn)
        self.pushButton_2.clicked.connect(self.txtEditor1.zoomOut)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSetDoc.setText(_translate("MainWindow", "setDocument"))
        self.btnClear.setText(_translate("MainWindow", "clear"))
        self.pushButton.setText(_translate("MainWindow", "Zoom in"))
        self.pushButton_2.setText(_translate("MainWindow", "Zomm out"))
        self.btnLoad.setText(_translate("MainWindow", "파일로드"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
