# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(262, 85)
        self.btn_w = QtWidgets.QPushButton(Dialog)
        self.btn_w.setGeometry(QtCore.QRect(10, 10, 111, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/흰배경.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_w.setIcon(icon)
        self.btn_w.setIconSize(QtCore.QSize(40, 40))
        self.btn_w.setObjectName("btn_w")
        self.btn_black = QtWidgets.QPushButton(Dialog)
        self.btn_black.setGeometry(QtCore.QRect(130, 10, 111, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/검은배경.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_black.setIcon(icon1)
        self.btn_black.setIconSize(QtCore.QSize(40, 40))
        self.btn_black.setObjectName("btn_black")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_w.setText(_translate("Dialog", "흰색배경"))
        self.btn_black.setText(_translate("Dialog", "검정배경"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
