# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(80, 10, 540, 780))
        self.textEdit.setMinimumSize(QtCore.QSize(540, 780))
        self.textEdit.setMaximumSize(QtCore.QSize(540, 780))
        self.textEdit.setBaseSize(QtCore.QSize(1000, 717))
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.lbl_image = QtWidgets.QLabel(self.centralwidget)
        self.lbl_image.setGeometry(QtCore.QRect(630, 10, 500, 717))
        self.lbl_image.setMaximumSize(QtCore.QSize(500, 717))
        self.lbl_image.setText("")
        self.lbl_image.setPixmap(QtGui.QPixmap(":/image/image_iner.jpg"))
        self.lbl_image.setScaledContents(True)
        self.lbl_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_image.setObjectName("lbl_image")
        self.btn_setting = QtWidgets.QPushButton(self.centralwidget)
        self.btn_setting.setGeometry(QtCore.QRect(10, 130, 51, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/setting.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_setting.setIcon(icon)
        self.btn_setting.setIconSize(QtCore.QSize(50, 50))
        self.btn_setting.setAutoRepeat(False)
        self.btn_setting.setObjectName("btn_setting")
        self.btn_setting_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_setting_2.setGeometry(QtCore.QRect(10, 20, 51, 51))
        self.btn_setting_2.setIcon(icon)
        self.btn_setting_2.setIconSize(QtCore.QSize(50, 50))
        self.btn_setting_2.setAutoRepeat(False)
        self.btn_setting_2.setObjectName("btn_setting_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 70, 61, 31))
        self.label.setStyleSheet("font: 8pt \"휴먼둥근헤드라인\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 31, 21))
        self.label_2.setStyleSheet("font: 8pt \"휴먼둥근헤드라인\";")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 800, 521, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Left = QtWidgets.QToolButton(self.widget)
        self.btn_Left.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btn_Left.setArrowType(QtCore.Qt.LeftArrow)
        self.btn_Left.setObjectName("btn_Left")
        self.horizontalLayout.addWidget(self.btn_Left)
        self.lblPage = QtWidgets.QLabel(self.widget)
        self.lblPage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPage.setObjectName("lblPage")
        self.horizontalLayout.addWidget(self.lblPage)
        self.btn_Right = QtWidgets.QToolButton(self.widget)
        self.btn_Right.setArrowType(QtCore.Qt.RightArrow)
        self.btn_Right.setObjectName("btn_Right")
        self.horizontalLayout.addWidget(self.btn_Right)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile_F = QtWidgets.QMenu(self.menubar)
        self.menuFile_F.setObjectName("menuFile_F")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile_F.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile_F.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Viewer"))
        self.label.setText(_translate("MainWindow", "배경글자색"))
        self.label_2.setText(_translate("MainWindow", "폰 트"))
        self.btn_Left.setText(_translate("MainWindow", "..."))
        self.lblPage.setText(_translate("MainWindow", "TextLabel"))
        self.btn_Right.setText(_translate("MainWindow", "..."))
        self.menuFile_F.setTitle(_translate("MainWindow", "File(&F)"))
        self.actionOpen.setText(_translate("MainWindow", "열기"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
import image_iner_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
