# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(293, 244)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.btnOption = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOption.sizePolicy().hasHeightForWidth())
        self.btnOption.setSizePolicy(sizePolicy)
        self.btnOption.setObjectName("btnOption")
        self.verticalLayout_3.addWidget(self.btnOption)
        self.btnOpen = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpen.sizePolicy().hasHeightForWidth())
        self.btnOpen.setSizePolicy(sizePolicy)
        self.btnOpen.setObjectName("btnOpen")
        self.verticalLayout_3.addWidget(self.btnOpen)
        self.btnGetColor = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGetColor.sizePolicy().hasHeightForWidth())
        self.btnGetColor.setSizePolicy(sizePolicy)
        self.btnGetColor.setObjectName("btnGetColor")
        self.verticalLayout_3.addWidget(self.btnGetColor)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblSelect = QtWidgets.QLabel(self.centralwidget)
        self.lblSelect.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblSelect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblSelect.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSelect.setObjectName("lblSelect")
        self.verticalLayout_2.addWidget(self.lblSelect)
        self.lblChange = QtWidgets.QLabel(self.centralwidget)
        self.lblChange.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblChange.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblChange.setAlignment(QtCore.Qt.AlignCenter)
        self.lblChange.setObjectName("lblChange")
        self.verticalLayout_2.addWidget(self.lblChange)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 293, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.checkBox.setText(_translate("MainWindow", "ShowAlphaChannel"))
        self.checkBox_2.setText(_translate("MainWindow", "NoButtons"))
        self.checkBox_3.setText(_translate("MainWindow", "DontUseNativeDialog"))
        self.btnOption.setText(_translate("MainWindow", "Option"))
        self.btnOpen.setText(_translate("MainWindow", "Open"))
        self.btnGetColor.setText(_translate("MainWindow", "getColor"))
        self.lblSelect.setText(_translate("MainWindow", "selected"))
        self.lblChange.setText(_translate("MainWindow", "changed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
